[package]
name = "handler"
version = "0.1.0"
authors = ["Gnaphron <gnaphron@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.13"
gstreamer = { version = "0.16", features = ["serde", "v1_14"] }
